### ISSUE TITLE
server documentation needs to be written

### ISSUE THREAD

**Issue by patrikrydberg** [xmetdb/xmetdb-server#24]
in Wiki form or something similar a complete documentation needs to be written

I suggest we start on the GitHub wiki and then transfer it to the xmetdb site. How should it be included on the final site? A wiki format would allow users to add information on enzymes and their reactions which could be helpful when a new specialist joins as user/curator.

What should be in the documentation?
Purpose of server
User and curator system functionality
all export functionality
API documentation
atom mapping instructions for all enzymatic reactions (or at least those we understand)
anything else?

**Comment by vedina** [comment]
Available at http://www.xmetdb.org/wiki
