### ISSUE TITLE
Enhance "Statistics" with #enzymes and #observations

### ISSUE THREAD

**Issue by egonw** [xmetdb/xmetdb-server#35]
It would be nice to also list the number of unique enzymes in the database, as well as the number of observations or better, the number of unique reactions.

**Comment by egonw** [comment]
@vedina, it seems to me this is implemented now, not? The number of unique reactions is not so important.

**Comment by vedina** [comment]
Yes, available in 0.0.4
![image](https://cloud.githubusercontent.com/assets/211190/6458865/4d906754-c191-11e4-9b25-3c9e7c88a82a.png)
