### ISSUE TITLE
search results stats and next/prev at bottom too

### ISSUE THREAD

**Issue by egonw** [xmetdb/xmetdb-server#39]
Currently, only at the top of a search result table, I get something like:

"Showing 1 to 10 of 61 entries First Previous 1 2 3 4 5 Next Last"

But when browsing the table, I end up at the bottom of the table (and page) and then want to go to the next page, but there is no such line there, so that I am annoyed to have to scroll back to the top again, just to see the next results...

**Comment by vedina** [comment]
Implemented, will be available in the v0.0.5

**Comment by egonw** [comment]
Yes, looks good in the dev version!
