### ISSUE TITLE
Have a help function for "Chemical Identifier" 

### ISSUE THREAD

**Issue by egonw** [xmetdb/xmetdb-server#40]
.. in the structure submission bit, showing two or three accepted identifiers. For example, entering an InChIKey has no effect, nor do I get any feedback on whether it is wrong, not found, or something else.

![xmetdb1](https://f.cloud.github.com/assets/26721/937611/c0cc7d38-00e1-11e3-9115-496d1c108a58.png)

**Comment by vedina** [comment]
This is available in v0.0.4
