### ISSUE TITLE
Please rename "Modify SOM" to "Modify Sites of Metabolism"

### ISSUE THREAD

**Issue by egonw** [xmetdb/xmetdb-server#41]
SOM means self-organizing map to me :)

![xmetdb2](https://f.cloud.github.com/assets/26721/937667/5092b930-00e4-11e3-82ea-57f17266b5e4.png)

**Comment by vedina** [comment]
Title changed in the development version

![image](https://cloud.githubusercontent.com/assets/211190/6460302/aeeb4e30-c19e-11e4-8c6e-48884c9728cf.png)
