### ISSUE TITLE
Ability to add links out for observations

### ISSUE THREAD

**Issue by egonw** [xmetdb/xmetdb-server#53]
I see two kinds of links:

- links to entries that say something about this particular reaction, e.g. a pathway in which this reaction takes place
- links to db entries matching this specific reaction (e.g. a CYP reaction in DrugBank)

**Comment by vedina** [comment]
Initial support implemented in the [development version](http://ambit.uni-plovdiv.bg:8080/xmetdb/protocol/XMETDB2/link) 

TODO: update UI and enable adding links via the UI

**Comment by vedina** [comment]
@egonw, please [have a look](http://ambit.uni-plovdiv.bg:8080/xmetdb/protocol/XMETDB1) - the "Related links" link

**Comment by egonw** [comment]
Nice!

**Comment by vedina** [comment]
Closing this then :) 
I'm sure the UI can be improved (in the next version)
