### ISSUE TITLE
For HEP experiments, it should not report "null null" for the enzyme

### ISSUE THREAD

**Issue by egonw** [xmetdb/xmetdb-server#56]
For HEP experiments, it should not report "null null" for the enzyme:

![image](https://cloud.githubusercontent.com/assets/26721/6458870/f9d854e4-c188-11e4-9ab4-176f6d7c0536.png)

**Comment by vedina** [comment]
Fixed in the [dev version](http://ambit.uni-plovdiv.bg:8080/xmetdb)

**Comment by egonw** [comment]
Confirmed fixed.
